

if(NOT DEFINED PMAC_PACKAGE_PATH)
     execute_process(COMMAND rospack find pmac OUTPUT_VARIABLE PMAC_PACKAGE_PATH  OUTPUT_STRIP_TRAILING_WHITESPACE)
     set(PMAC_PACKAGE_PATH ${PMAC_PACKAGE_PATH} CACHE PATH "PATH TO PMAC-PACKAGE")
endif(NOT DEFINED PMAC_PACKAGE_PATH)

message(STATUS "PMAC_PACKAGE_PATH: " ${PMAC_PACKAGE_PATH})

find_path(Pmac_INCLUDE_DIRS NAMES pmac.h HINTS ${PMAC_PACKAGE_PATH}/include/pmac)
message(STATUS "Pmac_INCLUDE_DIRS: " ${Pmac_INCLUDE_DIRS})

find_library(Pmac_LIBRARIES NAMES pmac HINTS ${PMAC_PACKAGE_PATH}/lib)
message(STATUS "Pmac_LIBRARIES: " ${Pmac_LIBRARIES})

set(Pmac_FOUND FALSE)

if(Pmac_INCLUDE_DIRS AND Pmac_LIBRARIES)
     set(Pmac_FOUND TRUE)
endif(Pmac_INCLUDE_DIRS AND Pmac_LIBRARIES)
