set(OpenMRL_PATH "${PROJECT_SOURCE_DIR}/../openmrl" CACHE PATH "Path to the openmrl folder")
MESSAGE(STATUS "OpenMRL_PATH: " ${OpenMRL_PATH})

find_path(OpenMRL_INCLUDE_DIRS NAMES config.h HINTS ${OpenMRL_PATH}/src)
MESSAGE(STATUS "OpenMRL_INCLUDE_DIRS: " ${OpenMRL_INCLUDE_DIRS})

find_library(OpenMRL_LIBRARIES NAMES mrl HINTS ${OpenMRL_PATH}/build/lib)
MESSAGE(STATUS "OpenMRL_LIBRARIES: " ${OpenMRL_LIBRARIES})

set(MRL_FOUND FALSE)

IF(OpenMRL_INCLUDE_DIRS AND OpenMRL_LIBRARIES)
     SET(MRL_FOUND TRUE)
ENDIF(OpenMRL_INCLUDE_DIRS AND OpenMRL_LIBRARIES)
