INCLUDE(${OpenMRL_CMAKE_MODULE_PATH}/utils.cmake)

#LIB JPEG
INCLUDE(FindJPEG)
IF(JPEG_FOUND)
	MESSAGE(STATUS "JPEG support is available")
	MESSAGE(STATUS "JPEG Libraries: " ${JPEG_LIBRARIES})
	MESSAGE(STATUS "JPEG Include dir: " ${JPEG_INCLUDE_DIR})
	INCLUDE_DIRECTORIES(JPEG_INCLUDE_DIR)
ELSE(JPEG_FOUND)
	MESSAGE(STATUS "JPEG NOT FOUND, but it is NOT required.")
ENDIF(JPEG_FOUND)

#LIB CWIID
INCLUDE(${OpenMRL_CMAKE_MODULE_PATH}/FindCWiid.cmake)
IF(CWIID_FOUND)
	MESSAGE(STATUS "CWIID support is available")
	MESSAGE(STATUS "CWIID Libraries: " ${CWIID_LIBRARIES})
	MESSAGE(STATUS "CWIID Include dir: " ${CWIID_INCLUDE_DIR})
	INCLUDE_DIRECTORIES(CWIID_INCLUDE_DIR)
ELSE(CWIID_FOUND)
	MESSAGE(STATUS "CWIID NOT FOUND, but it is NOT required.")
ENDIF(CWIID_FOUND)


#OPENGL
INCLUDE(FindOpenGL)
IF(OPENGL_FOUND)
	MESSAGE(STATUS "OpenGL support is available")
	MESSAGE(STATUS "OpenGL Libraries: " ${OPENGL_LIBRARIES})
	INCLUDE_DIRECTORIES(OPENGL_INCLUDE_DIR)
ELSE(OPENGL_FOUND)
	MESSAGE(ERROR "OpenGL NOT FOUND, but IT IS required. Please install")
ENDIF(OPENGL_FOUND)


INCLUDE(${OpenMRL_CMAKE_MODULE_PATH}/FindGlut.cmake)
	IF(GLUT_FOUND)
		MESSAGE(STATUS "GLUT support is available")
		MESSAGE(STATUS "Glut Header: " ${GLUT_INCLUDE_DIR})
		MESSAGE(STATUS "Glut Libraries: " ${GLUT_LIBRARIES})
		INCLUDE_DIRECTORIES(GLUT_INCLUDE_DIR)
	ELSE(GLUT_FOUND)
		MESSAGE(ERROR "GLUT not found. But IT IS required")
	ENDIF(GLUT_FOUND)

INCLUDE (${OpenMRL_CMAKE_MODULE_PATH}/CheckFunctionExists.cmake)
	MESSAGE(STATUS "Checking time functions")
	check_function_exists(gettimeofday HAVE_GETTIMEOFDAY)
	check_function_exists(clock_gettime HAVE_CLOCK_GETTIME)






