# This will force any user change or any configuration
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMPILATION_FLAGS} -Wl,--no-as-needed")

IF("${OpenRDK_ARCH}" STREQUAL "geode")
	SET(COMPILE_RCONSOLE 0)
	SET(COMPILE_USARSIM_SECTIONS 0)
	SET(COMPILE_NAO_SECTIONS 1)
	STRING(REGEX REPLACE "-O." "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
ELSEIF("${OpenRDK_ARCH}" STREQUAL "arm9")
	SET(COMPILE_RCONSOLE 0)
	SET(COMPILE_NAO_SECTIONS 0)
ENDIF("${OpenRDK_ARCH}" STREQUAL "geode")

if(CMAKE_BUILD_TYPE STREQUAL "")
	SET(CMAKE_BUILD_TYPE "DEBUG" CACHE STRING "Building configuration" FORCE)
endif(CMAKE_BUILD_TYPE STREQUAL "")

if(NOT "${CMAKE_SYSTEM}" MATCHES "CYGWIN")
	set(CMAKE_INSTALL_PREFIX "${OpenRDK_OUTPUT_TREE}" CACHE PATH "" FORCE)
	get_filename_component(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_INSTALL_PREFIX}/lib" ABSOLUTE)
	get_filename_component(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_INSTALL_PREFIX}/lib" ABSOLUTE)
	get_filename_component(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_INSTALL_PREFIX}/bin" ABSOLUTE)
	get_filename_component(OpenRDK_RESOURCES "${OpenRDK_ROOT}/docs" ABSOLUTE)
endif(NOT "${CMAKE_SYSTEM}" MATCHES "CYGWIN")

