; Auto-generated. Do not edit!


(cl:in-package manfred_arm_msgs-msg)


;//! \htmlinclude LocalizacionEvolucionDiferencialResult.msg.html

(cl:defclass <LocalizacionEvolucionDiferencialResult> (roslisp-msg-protocol:ros-message)
  ((ubicacionRobotSRG
    :reader ubicacionRobotSRG
    :initarg :ubicacionRobotSRG
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass LocalizacionEvolucionDiferencialResult (<LocalizacionEvolucionDiferencialResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LocalizacionEvolucionDiferencialResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LocalizacionEvolucionDiferencialResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name manfred_arm_msgs-msg:<LocalizacionEvolucionDiferencialResult> is deprecated: use manfred_arm_msgs-msg:LocalizacionEvolucionDiferencialResult instead.")))

(cl:ensure-generic-function 'ubicacionRobotSRG-val :lambda-list '(m))
(cl:defmethod ubicacionRobotSRG-val ((m <LocalizacionEvolucionDiferencialResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader manfred_arm_msgs-msg:ubicacionRobotSRG-val is deprecated.  Use manfred_arm_msgs-msg:ubicacionRobotSRG instead.")
  (ubicacionRobotSRG m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LocalizacionEvolucionDiferencialResult>) ostream)
  "Serializes a message object of type '<LocalizacionEvolucionDiferencialResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'ubicacionRobotSRG) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LocalizacionEvolucionDiferencialResult>) istream)
  "Deserializes a message object of type '<LocalizacionEvolucionDiferencialResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'ubicacionRobotSRG) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LocalizacionEvolucionDiferencialResult>)))
  "Returns string type for a message object of type '<LocalizacionEvolucionDiferencialResult>"
  "manfred_arm_msgs/LocalizacionEvolucionDiferencialResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LocalizacionEvolucionDiferencialResult)))
  "Returns string type for a message object of type 'LocalizacionEvolucionDiferencialResult"
  "manfred_arm_msgs/LocalizacionEvolucionDiferencialResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LocalizacionEvolucionDiferencialResult>)))
  "Returns md5sum for a message object of type '<LocalizacionEvolucionDiferencialResult>"
  "1701744b09a02096bc944abf6a274dba")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LocalizacionEvolucionDiferencialResult)))
  "Returns md5sum for a message object of type 'LocalizacionEvolucionDiferencialResult"
  "1701744b09a02096bc944abf6a274dba")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LocalizacionEvolucionDiferencialResult>)))
  "Returns full string definition for message of type '<LocalizacionEvolucionDiferencialResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%# Ubicación del robot en el sistema de referencia global (SRG)~%geometry_msgs/PoseStamped ubicacionRobotSRG~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LocalizacionEvolucionDiferencialResult)))
  "Returns full string definition for message of type 'LocalizacionEvolucionDiferencialResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%# Ubicación del robot en el sistema de referencia global (SRG)~%geometry_msgs/PoseStamped ubicacionRobotSRG~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LocalizacionEvolucionDiferencialResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'ubicacionRobotSRG))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LocalizacionEvolucionDiferencialResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LocalizacionEvolucionDiferencialResult
    (cl:cons ':ubicacionRobotSRG (ubicacionRobotSRG msg))
))
