; Auto-generated. Do not edit!


(cl:in-package manfred_arm_msgs-msg)


;//! \htmlinclude LocalizacionEvolucionDiferencialGoal.msg.html

(cl:defclass <LocalizacionEvolucionDiferencialGoal> (roslisp-msg-protocol:ros-message)
  ((dummyFlagGoal
    :reader dummyFlagGoal
    :initarg :dummyFlagGoal
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass LocalizacionEvolucionDiferencialGoal (<LocalizacionEvolucionDiferencialGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LocalizacionEvolucionDiferencialGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LocalizacionEvolucionDiferencialGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name manfred_arm_msgs-msg:<LocalizacionEvolucionDiferencialGoal> is deprecated: use manfred_arm_msgs-msg:LocalizacionEvolucionDiferencialGoal instead.")))

(cl:ensure-generic-function 'dummyFlagGoal-val :lambda-list '(m))
(cl:defmethod dummyFlagGoal-val ((m <LocalizacionEvolucionDiferencialGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader manfred_arm_msgs-msg:dummyFlagGoal-val is deprecated.  Use manfred_arm_msgs-msg:dummyFlagGoal instead.")
  (dummyFlagGoal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LocalizacionEvolucionDiferencialGoal>) ostream)
  "Serializes a message object of type '<LocalizacionEvolucionDiferencialGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'dummyFlagGoal) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LocalizacionEvolucionDiferencialGoal>) istream)
  "Deserializes a message object of type '<LocalizacionEvolucionDiferencialGoal>"
    (cl:setf (cl:slot-value msg 'dummyFlagGoal) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LocalizacionEvolucionDiferencialGoal>)))
  "Returns string type for a message object of type '<LocalizacionEvolucionDiferencialGoal>"
  "manfred_arm_msgs/LocalizacionEvolucionDiferencialGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LocalizacionEvolucionDiferencialGoal)))
  "Returns string type for a message object of type 'LocalizacionEvolucionDiferencialGoal"
  "manfred_arm_msgs/LocalizacionEvolucionDiferencialGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LocalizacionEvolucionDiferencialGoal>)))
  "Returns md5sum for a message object of type '<LocalizacionEvolucionDiferencialGoal>"
  "96e4e09f1d65f85c4452bd9a4f16ee7b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LocalizacionEvolucionDiferencialGoal)))
  "Returns md5sum for a message object of type 'LocalizacionEvolucionDiferencialGoal"
  "96e4e09f1d65f85c4452bd9a4f16ee7b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LocalizacionEvolucionDiferencialGoal>)))
  "Returns full string definition for message of type '<LocalizacionEvolucionDiferencialGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool dummyFlagGoal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LocalizacionEvolucionDiferencialGoal)))
  "Returns full string definition for message of type 'LocalizacionEvolucionDiferencialGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool dummyFlagGoal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LocalizacionEvolucionDiferencialGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LocalizacionEvolucionDiferencialGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LocalizacionEvolucionDiferencialGoal
    (cl:cons ':dummyFlagGoal (dummyFlagGoal msg))
))
