; Auto-generated. Do not edit!


(cl:in-package manfred_arm_msgs-msg)


;//! \htmlinclude LocalizacionEvolucionDiferencialActionGoal.msg.html

(cl:defclass <LocalizacionEvolucionDiferencialActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type manfred_arm_msgs-msg:LocalizacionEvolucionDiferencialGoal
    :initform (cl:make-instance 'manfred_arm_msgs-msg:LocalizacionEvolucionDiferencialGoal)))
)

(cl:defclass LocalizacionEvolucionDiferencialActionGoal (<LocalizacionEvolucionDiferencialActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LocalizacionEvolucionDiferencialActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LocalizacionEvolucionDiferencialActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name manfred_arm_msgs-msg:<LocalizacionEvolucionDiferencialActionGoal> is deprecated: use manfred_arm_msgs-msg:LocalizacionEvolucionDiferencialActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <LocalizacionEvolucionDiferencialActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader manfred_arm_msgs-msg:header-val is deprecated.  Use manfred_arm_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <LocalizacionEvolucionDiferencialActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader manfred_arm_msgs-msg:goal_id-val is deprecated.  Use manfred_arm_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <LocalizacionEvolucionDiferencialActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader manfred_arm_msgs-msg:goal-val is deprecated.  Use manfred_arm_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LocalizacionEvolucionDiferencialActionGoal>) ostream)
  "Serializes a message object of type '<LocalizacionEvolucionDiferencialActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LocalizacionEvolucionDiferencialActionGoal>) istream)
  "Deserializes a message object of type '<LocalizacionEvolucionDiferencialActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LocalizacionEvolucionDiferencialActionGoal>)))
  "Returns string type for a message object of type '<LocalizacionEvolucionDiferencialActionGoal>"
  "manfred_arm_msgs/LocalizacionEvolucionDiferencialActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LocalizacionEvolucionDiferencialActionGoal)))
  "Returns string type for a message object of type 'LocalizacionEvolucionDiferencialActionGoal"
  "manfred_arm_msgs/LocalizacionEvolucionDiferencialActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LocalizacionEvolucionDiferencialActionGoal>)))
  "Returns md5sum for a message object of type '<LocalizacionEvolucionDiferencialActionGoal>"
  "96263df5f82f2db39da0eb1546e79712")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LocalizacionEvolucionDiferencialActionGoal)))
  "Returns md5sum for a message object of type 'LocalizacionEvolucionDiferencialActionGoal"
  "96263df5f82f2db39da0eb1546e79712")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LocalizacionEvolucionDiferencialActionGoal>)))
  "Returns full string definition for message of type '<LocalizacionEvolucionDiferencialActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%LocalizacionEvolucionDiferencialGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: manfred_arm_msgs/LocalizacionEvolucionDiferencialGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool dummyFlagGoal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LocalizacionEvolucionDiferencialActionGoal)))
  "Returns full string definition for message of type 'LocalizacionEvolucionDiferencialActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%LocalizacionEvolucionDiferencialGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: manfred_arm_msgs/LocalizacionEvolucionDiferencialGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool dummyFlagGoal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LocalizacionEvolucionDiferencialActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LocalizacionEvolucionDiferencialActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LocalizacionEvolucionDiferencialActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
