/* Auto-generated by genmsg_cpp for file /home/disa1301/Documents/Codigo/Manfred/ros/manfred_arm_msgs/srv/Get_IK_ed.srv */
#ifndef MANFRED_ARM_MSGS_SERVICE_GET_IK_ED_H
#define MANFRED_ARM_MSGS_SERVICE_GET_IK_ED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "sensor_msgs/JointState.h"
#include "geometry_msgs/Point32.h"
#include "geometry_msgs/Vector3.h"


#include "sensor_msgs/JointState.h"

namespace manfred_arm_msgs
{
template <class ContainerAllocator>
struct Get_IK_edRequest_ {
  typedef Get_IK_edRequest_<ContainerAllocator> Type;

  Get_IK_edRequest_()
  : joint_state()
  , goal_posic()
  , goal_rpy()
  {
  }

  Get_IK_edRequest_(const ContainerAllocator& _alloc)
  : joint_state(_alloc)
  , goal_posic(_alloc)
  , goal_rpy(_alloc)
  {
  }

  typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joint_state_type;
   ::sensor_msgs::JointState_<ContainerAllocator>  joint_state;

  typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _goal_posic_type;
   ::geometry_msgs::Point32_<ContainerAllocator>  goal_posic;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _goal_rpy_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  goal_rpy;


  typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Get_IK_edRequest
typedef  ::manfred_arm_msgs::Get_IK_edRequest_<std::allocator<void> > Get_IK_edRequest;

typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IK_edRequest> Get_IK_edRequestPtr;
typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IK_edRequest const> Get_IK_edRequestConstPtr;


template <class ContainerAllocator>
struct Get_IK_edResponse_ {
  typedef Get_IK_edResponse_<ContainerAllocator> Type;

  Get_IK_edResponse_()
  : joint_state()
  , x_final(0.0)
  , y_final(0.0)
  , error_code(0)
  {
  }

  Get_IK_edResponse_(const ContainerAllocator& _alloc)
  : joint_state(_alloc)
  , x_final(0.0)
  , y_final(0.0)
  , error_code(0)
  {
  }

  typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joint_state_type;
   ::sensor_msgs::JointState_<ContainerAllocator>  joint_state;

  typedef double _x_final_type;
  double x_final;

  typedef double _y_final_type;
  double y_final;

  typedef int64_t _error_code_type;
  int64_t error_code;


  typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Get_IK_edResponse
typedef  ::manfred_arm_msgs::Get_IK_edResponse_<std::allocator<void> > Get_IK_edResponse;

typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IK_edResponse> Get_IK_edResponsePtr;
typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IK_edResponse const> Get_IK_edResponseConstPtr;

struct Get_IK_ed
{

typedef Get_IK_edRequest Request;
typedef Get_IK_edResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Get_IK_ed
} // namespace manfred_arm_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "760796620ca3ae391fea994012fa4378";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x760796620ca3ae39ULL;
  static const uint64_t static_value2 = 0x1fea994012fa4378ULL;
};

template<class ContainerAllocator>
struct DataType< ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IK_edRequest";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
\n\
sensor_msgs/JointState joint_state\n\
\n\
\n\
\n\
\n\
geometry_msgs/Point32 goal_posic\n\
geometry_msgs/Vector3 goal_rpy\n\
\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f21ed637920e57f4913f1f31d9b36424";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf21ed637920e57f4ULL;
  static const uint64_t static_value2 = 0x913f1f31d9b36424ULL;
};

template<class ContainerAllocator>
struct DataType< ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IK_edResponse";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
sensor_msgs/JointState joint_state\n\
float64 x_final\n\
float64 y_final\n\
\n\
int64 error_code\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joint_state);
    stream.next(m.goal_posic);
    stream.next(m.goal_rpy);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Get_IK_edRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joint_state);
    stream.next(m.x_final);
    stream.next(m.y_final);
    stream.next(m.error_code);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Get_IK_edResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<manfred_arm_msgs::Get_IK_ed> {
  static const char* value() 
  {
    return "754c918dc2becdc6d02d215fd79aba93";
  }

  static const char* value(const manfred_arm_msgs::Get_IK_ed&) { return value(); } 
};

template<>
struct DataType<manfred_arm_msgs::Get_IK_ed> {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IK_ed";
  }

  static const char* value(const manfred_arm_msgs::Get_IK_ed&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "754c918dc2becdc6d02d215fd79aba93";
  }

  static const char* value(const manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IK_ed";
  }

  static const char* value(const manfred_arm_msgs::Get_IK_edRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "754c918dc2becdc6d02d215fd79aba93";
  }

  static const char* value(const manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IK_ed";
  }

  static const char* value(const manfred_arm_msgs::Get_IK_edResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MANFRED_ARM_MSGS_SERVICE_GET_IK_ED_H

