/* Auto-generated by genmsg_cpp for file /home/disa1301/Documents/Codigo/Manfred/ros/manfred_arm_msgs/srv/Get_IK.srv */
#ifndef MANFRED_ARM_MSGS_SERVICE_GET_IK_H
#define MANFRED_ARM_MSGS_SERVICE_GET_IK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "sensor_msgs/JointState.h"
#include "geometry_msgs/Twist.h"


#include "sensor_msgs/JointState.h"

namespace manfred_arm_msgs
{
template <class ContainerAllocator>
struct Get_IKRequest_ {
  typedef Get_IKRequest_<ContainerAllocator> Type;

  Get_IKRequest_()
  : joint_state()
  , twist()
  {
  }

  Get_IKRequest_(const ContainerAllocator& _alloc)
  : joint_state(_alloc)
  , twist(_alloc)
  {
  }

  typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joint_state_type;
   ::sensor_msgs::JointState_<ContainerAllocator>  joint_state;

  typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
   ::geometry_msgs::Twist_<ContainerAllocator>  twist;


  typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Get_IKRequest
typedef  ::manfred_arm_msgs::Get_IKRequest_<std::allocator<void> > Get_IKRequest;

typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IKRequest> Get_IKRequestPtr;
typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IKRequest const> Get_IKRequestConstPtr;


template <class ContainerAllocator>
struct Get_IKResponse_ {
  typedef Get_IKResponse_<ContainerAllocator> Type;

  Get_IKResponse_()
  : joint_state()
  , error_code(0)
  {
  }

  Get_IKResponse_(const ContainerAllocator& _alloc)
  : joint_state(_alloc)
  , error_code(0)
  {
  }

  typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joint_state_type;
   ::sensor_msgs::JointState_<ContainerAllocator>  joint_state;

  typedef int64_t _error_code_type;
  int64_t error_code;


  typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Get_IKResponse
typedef  ::manfred_arm_msgs::Get_IKResponse_<std::allocator<void> > Get_IKResponse;

typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IKResponse> Get_IKResponsePtr;
typedef boost::shared_ptr< ::manfred_arm_msgs::Get_IKResponse const> Get_IKResponseConstPtr;

struct Get_IK
{

typedef Get_IKRequest Request;
typedef Get_IKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Get_IK
} // namespace manfred_arm_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e44e1f8749cd750c610eacc0a2fce255";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe44e1f8749cd750cULL;
  static const uint64_t static_value2 = 0x610eacc0a2fce255ULL;
};

template<class ContainerAllocator>
struct DataType< ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IKRequest";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
\n\
sensor_msgs/JointState joint_state\n\
\n\
\n\
geometry_msgs/Twist twist\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f4bdee3e3858d66a1df599b51bb85a7a";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf4bdee3e3858d66aULL;
  static const uint64_t static_value2 = 0x1df599b51bb85a7aULL;
};

template<class ContainerAllocator>
struct DataType< ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IKResponse";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
sensor_msgs/JointState joint_state\n\
\n\
int64 error_code\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joint_state);
    stream.next(m.twist);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Get_IKRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joint_state);
    stream.next(m.error_code);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Get_IKResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<manfred_arm_msgs::Get_IK> {
  static const char* value() 
  {
    return "04eb813c112330e9a270b1021059941d";
  }

  static const char* value(const manfred_arm_msgs::Get_IK&) { return value(); } 
};

template<>
struct DataType<manfred_arm_msgs::Get_IK> {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IK";
  }

  static const char* value(const manfred_arm_msgs::Get_IK&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "04eb813c112330e9a270b1021059941d";
  }

  static const char* value(const manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IK";
  }

  static const char* value(const manfred_arm_msgs::Get_IKRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "04eb813c112330e9a270b1021059941d";
  }

  static const char* value(const manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manfred_arm_msgs/Get_IK";
  }

  static const char* value(const manfred_arm_msgs::Get_IKResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MANFRED_ARM_MSGS_SERVICE_GET_IK_H

