/* Auto-generated by genmsg_cpp for file /home/disa1301/Documents/Codigo/Manfred/ros/manfred_arm_msgs/msg/LocalizacionEvolucionDiferencialResult.msg */
#ifndef MANFRED_ARM_MSGS_MESSAGE_LOCALIZACIONEVOLUCIONDIFERENCIALRESULT_H
#define MANFRED_ARM_MSGS_MESSAGE_LOCALIZACIONEVOLUCIONDIFERENCIALRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PoseStamped.h"

namespace manfred_arm_msgs
{
template <class ContainerAllocator>
struct LocalizacionEvolucionDiferencialResult_ {
  typedef LocalizacionEvolucionDiferencialResult_<ContainerAllocator> Type;

  LocalizacionEvolucionDiferencialResult_()
  : ubicacionRobotSRG()
  {
  }

  LocalizacionEvolucionDiferencialResult_(const ContainerAllocator& _alloc)
  : ubicacionRobotSRG(_alloc)
  {
  }

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _ubicacionRobotSRG_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  ubicacionRobotSRG;


  typedef boost::shared_ptr< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LocalizacionEvolucionDiferencialResult
typedef  ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<std::allocator<void> > LocalizacionEvolucionDiferencialResult;

typedef boost::shared_ptr< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult> LocalizacionEvolucionDiferencialResultPtr;
typedef boost::shared_ptr< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult const> LocalizacionEvolucionDiferencialResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace manfred_arm_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1701744b09a02096bc944abf6a274dba";
  }

  static const char* value(const  ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1701744b09a02096ULL;
  static const uint64_t static_value2 = 0xbc944abf6a274dbaULL;
};

template<class ContainerAllocator>
struct DataType< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "manfred_arm_msgs/LocalizacionEvolucionDiferencialResult";
  }

  static const char* value(const  ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
# Ubicación del robot en el sistema de referencia global (SRG)\n\
geometry_msgs/PoseStamped ubicacionRobotSRG\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ubicacionRobotSRG);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LocalizacionEvolucionDiferencialResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::manfred_arm_msgs::LocalizacionEvolucionDiferencialResult_<ContainerAllocator> & v) 
  {
    s << indent << "ubicacionRobotSRG: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.ubicacionRobotSRG);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MANFRED_ARM_MSGS_MESSAGE_LOCALIZACIONEVOLUCIONDIFERENCIALRESULT_H

